"""
Флажок быстрой регистрации у пользователей

Revision ID: 697876a4d7da
Revises: c4a91a006a2f
Create Date: 2021-08-30 08:39:26.338023

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '697876a4d7da'
down_revision = 'c4a91a006a2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('quick', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'quick')
    # ### end Alembic commands ###
