"""
Долгие сессии с помощью `Remember me`

Revision ID: 400bdd286fa4
Revises: daa42690de81
Create Date: 2021-07-17 21:43:42.568136

"""
from alembic import op
import sqlalchemy as sa
import cyberdas.utils.hash_type


# revision identifiers, used by Alembic.
revision = '400bdd286fa4'
down_revision = 'daa42690de81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('selector', sa.String(length=16), nullable=False),
    sa.Column('validator', cyberdas.utils.hash_type.HashType('sha256'), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=16), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name=op.f('fk_long_sessions_uid_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_long_sessions')),
    sa.UniqueConstraint('selector', name=op.f('uq_long_sessions_selector'))
    )
    op.add_column('sessions', sa.Column('unsafe', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'unsafe')
    op.drop_table('long_sessions')
    # ### end Alembic commands ###
