"""
Система очередей

Revision ID: 207c14670fcd
Revises: 1e2431b413e1
Create Date: 2021-08-11 00:24:38.278498

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '207c14670fcd'
down_revision = '1e2431b413e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queues',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('waterfall', sa.Boolean(), nullable=False),
    sa.Column('only_once', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name', name=op.f('pk_queues'))
    )
    op.create_table('slots',
    sa.Column('queue_name', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['queue_name'], ['queues.name'], name=op.f('fk_slots_queue_name_queues')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_slots_user_id_users')),
    sa.PrimaryKeyConstraint('queue_name', 'id', name=op.f('pk_slots'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slots')
    op.drop_table('queues')
    # ### end Alembic commands ###
