"""
Заявки на технические услуги

Revision ID: 225d734824cb
Revises: 9b517ddd1ca0
Create Date: 2021-09-19 23:33:15.122267

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '225d734824cb'
down_revision = '9b517ddd1ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=False),
    sa.Column('room', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_maintenances_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenances'))
    )
    op.add_column('users', sa.Column('building', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('room', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'room')
    op.drop_column('users', 'building')
    op.drop_table('maintenances')
    # ### end Alembic commands ###
