"""
Минорные изменения в пользователях

Revision ID: c4a91a006a2f
Revises: 37a06deaec23
Create Date: 2021-08-29 07:15:46.111499

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = 'c4a91a006a2f'
down_revision = '37a06deaec23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_session', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'last_session')
    # ### end Alembic commands ###
