"""
Ассоциирование сессий между собой

Revision ID: 1e2431b413e1
Revises: 400bdd286fa4
Create Date: 2021-07-18 05:22:01.157193

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '1e2431b413e1'
down_revision = '400bdd286fa4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('long_sessions', sa.Column('associated_sid', cyberdas.utils.hash_type.HashType(length=32), nullable=True))
    op.create_foreign_key(op.f('fk_long_sessions_associated_sid_sessions'), 'long_sessions', 'sessions', ['associated_sid'], ['sid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_long_sessions_associated_sid_sessions'), 'long_sessions', type_='foreignkey')
    op.drop_column('long_sessions', 'associated_sid')
    # ### end Alembic commands ###
