"""
Ревизия сессий

Revision ID: 71bcf0a63639
Revises: 875915bfbe8a
Create Date: 2021-07-14 15:25:36.157678

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '71bcf0a63639'
down_revision = '875915bfbe8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('sid', sa.String(), nullable=False),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('csrf_token', sa.String(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], name=op.f('fk_sessions_uid_users')),
    sa.PrimaryKeyConstraint('sid', name=op.f('pk_sessions')),
    sa.UniqueConstraint('csrf_token', name=op.f('uq_sessions_csrf_token'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions')
    # ### end Alembic commands ###
