"""
Поле 'курс' у пользователей

Revision ID: 22d32aac74f7
Revises: a9144fad477a
Create Date: 2021-09-02 07:34:41.857127

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '22d32aac74f7'
down_revision = 'a9144fad477a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('course', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'course')
    # ### end Alembic commands ###
