name: deploy-prod

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    defaults:
      run:
        working-directory: /usr/share/cyberdas
    steps:
      - name: Cleanup
        run: |
          rm -rf cyberdas-prod
      - name: Clone repo
        run: |
          git clone https://github.com/$GITHUB_REPOSITORY.git --branch ${GITHUB_REF##*/} --single-branch cyberdas-prod
      - name: Set secrets
        working-directory: /usr/share/cyberdas/cyberdas-prod
        run: |
          python3 -c "
          with open('cfg.ini', 'r+') as f:
              d = f.read()

              d = d\
              .replace('DB_URL', '"'${{ secrets.DB_URL_PROD }}'"')\
              .replace('DB_USER', '"'${{ secrets.DB_USER_PROD }}'"')\
              .replace('DB_PASS', '"'${{ secrets.DB_PASS_PROD }}'"')\
              .replace('DB_NAME', '"'${{ secrets.DB_NAME_PROD }}'"')\
              .replace('SEC_SIGNUP', '"'${{ secrets.SEC_SIGNUP_PROD }}'"')\
              .replace('SEC_AUTH', '"'${{ secrets.SEC_AUTH_PROD }}'"')\
              .replace('SALT_SIGNUP', '"'${{ secrets.SALT_SIGNUP_PROD }}'"')\
              .replace('EMAIL_FROM', '"'${{ secrets.EMAIL_FROM }}'"')\
              .replace('EMAIL_SERVER', '"'${{ secrets.EMAIL_SERVER }}'"')\
              .replace('EMAIL_PORT', '"'${{ secrets.EMAIL_PORT }}'"')\
              .replace('EMAIL_LOGIN', '"'${{ secrets.EMAIL_LOGIN }}'"')\
              .replace('EMAIL_PASS', '"'${{ secrets.EMAIL_PASS }}'"')

              f.seek(0)
              f.write(d)
              f.write('''
          [cdci]
          build = live
          ''')
              f.truncate()
              f.close()"
      - name: Install app
        working-directory: /usr/share/cyberdas/cyberdas-prod
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -e "."
      - name: Apply DB migrations
        working-directory: /usr/share/cyberdas/cyberdas-prod
        run: |
            source .venv/bin/activate
            alembic -c cfg.ini upgrade head
    
  deploy:
    needs: build
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Move new API specification
        working-directory: /usr/share/cyberdas/cyberdas-prod
        run: |
          mv openapi-spec.yml cyberdas/static/openapi-spec.yml
      - name: Restart service
        run: |
          sudo /bin/systemctl restart gunicorn_prod
      - name: Check status
        run: |
          sleep 5
          systemctl status gunicorn_prod
          
          if [ $? -eq 0 ]
          then 
            exit 0
          else
            echo "[ ERROR ] Service is not running"
            exit 1
          fi