name: deploy-next

on:
  push:
    branches: [ next ]

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: next
      - name: Set secrets
        working-directory: next
        run: |
          python3 -c "
          with open('cfg.ini', 'r+') as f:
              d = f.read()

              d = d\
              .replace('DB_URL', '"'${{ secrets.DB_URL_NEXT }}'"')\
              .replace('DB_USER', '"'${{ secrets.DB_USER_NEXT }}'"')\
              .replace('DB_PASS', '"'${{ secrets.DB_PASS_NEXT }}'"')\
              .replace('DB_NAME', '"'${{ secrets.DB_NAME_NEXT }}'"')\
              .replace('SEC_SIGNUP', '"'${{ secrets.SEC_SIGNUP_NEXT }}'"')\
              .replace('SEC_AUTH', '"'${{ secrets.SEC_AUTH_NEXT }}'"')\
              .replace('SALT_SIGNUP', '"'${{ secrets.SALT_SIGNUP_NEXT }}'"')\
              .replace('EMAIL_FROM', '"'${{ secrets.EMAIL_FROM }}'"')\
              .replace('EMAIL_SERVER', '"'${{ secrets.EMAIL_SERVER }}'"')\
              .replace('EMAIL_PORT', '"'${{ secrets.EMAIL_PORT }}'"')\
              .replace('EMAIL_LOGIN', '"'${{ secrets.EMAIL_LOGIN }}'"')\
              .replace('EMAIL_PASS', '"'${{ secrets.EMAIL_PASS }}'"')

              f.seek(0)
              f.write(d)
              f.write('''
          [cdci]
          build = next
          ''')
              f.truncate()
              f.close()"
      - name: Install app
        working-directory: next
        run: |
          python3.9 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip setuptools wheel
          pip install -e "."
      - name: Apply DB migrations
        working-directory: next
        run: |
            source .venv/bin/activate
            alembic -c cfg.ini upgrade head
    
  deploy:
    needs: build
    runs-on: [self-hosted, linux, X64]
    steps:
      - name: Move new API specification
        working-directory: next
        run: |
          mv openapi-spec.yml cyberdas/static/openapi-spec.yml
      - name: Restart service
        run: |
          sudo /bin/systemctl restart gunicorn_next
      - name: Check status
        run: |
          sleep 5
          systemctl status gunicorn_next
          
          if [ $? -eq 0 ]
          then 
            exit 0
          else
            echo "[ ERROR ] Service is not running"
            exit 1
          fi